### PR TITLE
enhance: add some useful utils & format code etc...

### PR DESCRIPTION
**Pull request by yuxino**
1. Add `format` in `package.json`
2. Add `husky` & `lint-staged` to auto format code when `pre-commit`
3. Add `commitlint` to lint commit messages
3. Modify `tabWidth` to 2 in `.prettierrc`
4. •̀ω•́)_ Formatted the original code once ..
5. When params is empty will show `v2 -v` default
6. Change preview image of docs

### CODE REVIEW

**Comment by yuxino** [comment]
Define some commit types as follows :

- :sparkles: feat: **msg**
- :package: new: **msg**
- :bug: fix: **msg**
- :gem: release: **msg**
- :memo: docs: **msg**
- :white_check_mark: test: **msg**
- :recycle: refactor: **msg**
- :hankey: bad: **msg**
- :tada: init: **msg**
- :fire: remove: **msg**
- :art: format: **msg**

If your commit does not follow the above rules, it will not be push. 

CC @thjiang

**Comment by thjiang** [comment]
Thanks for contributing, the commit hashed as 36149d4 has been merged.
I still prefer the current one in terms of code style, so I didn’t merge them all, hopefully you understand.

**Comment by yuxino** [comment]
@thjiang Will you accept a new pr when i reset code to 4 tabWidth style ? Like [this](https://github.com/yuxino/easyV2/commit/82c20f2b903e0d971b873450ae6fe6eb25dd2863)

**Comment by thjiang** [comment]
Certainly.
BTW, it's best to keep the preview for the time being. I'm going to provide color matching for two themes.

**Comment by thjiang** [comment]
> @thjiang Will you accept a new pr when i reset code to 4 tabWidth style ? Like [this](https://github.com/yuxino/easyV2/commit/82c20f2b903e0d971b873450ae6fe6eb25dd2863)

Certainly.
BTW, it's best to keep the preview for the time being. I'm going to provide color matching for two themes.

**Comment by yuxino** [comment]
@thjiang •̀ω•́)_ [Ok](https://github.com/yuxino/easyV2/commit/8a4b2889f951167611195e9eb36aeae0bb1cffd5).

**Comment by yuxino** [comment]
BTW. I think the comments are more comfortable in turn. Reading order should be from top to bottom. 

```
4# ddd
我觉得1楼说得对

3# zzz
我觉得2楼说得对

2# yyy
@xxx 巴拉巴拉啦

1# xxx
巴拉巴拉啦
```

The current order is like this. But it’s a bit inconvenient when the number of comments is large. We need to keep scrolling the mouse to know what did the previous person comment.

```
1# xxx
巴拉巴拉啦

2# yyy
@xxx 巴拉巴拉啦

3# zzz
我觉得2楼说得对

4# ddd
我觉得1楼说得对
```

**Pull request closed without merging**
